import type { Metadata } from "next";
import { Adamina } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layout/navigation-bar";
import Footer from "@/components/layout/footer";

const adamina = Adamina({
  variable: "--font-adamina",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "FJ Constructions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adamina.variable} antialiased`}
      >
        <div className="flex w-full items-center justify-center">
          <NavigationBar />
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
